# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 21:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('birthdate', models.DateTimeField(verbose_name='Fecha de Nacimiento')),
                ('dni', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Surgeon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Surgery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Fecha de Cirugía')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surgery.Patient')),
                ('surgeon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surgery.Surgeon')),
            ],
        ),
    ]
