# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 21:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surgery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='birthdate',
            field=models.DateField(verbose_name='Fecha de Nacimiento'),
        ),
    ]
